version: '3.8'

services:
  # MySQL数据库 - 存储用户会话和系统配置
  mysql:
    image: mysql:8.0
    container_name: aiops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: aiops123
      MYSQL_DATABASE: aiops
      MYSQL_USER: aiops_user
      MYSQL_PASSWORD: aiops_pass
    ports:
      - "3306:330    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aiops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # Neo4j图数据库 - 知识图谱存储
  neo4j:
    image: neo4j:5.15
    container_name: aiops-neo4j
    environment:
      NEO4J_AUTH: neo4j/aiops123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - aiops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "aiops123", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # Weaviate向量数据库 - 语义搜索
  weaviate:
    image: semitechnologies/weaviate:1.23.7
    container_name: aiops-weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - aiops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # Redis缓存 - 会话缓存和任务队列
  redis:
    image: redis:7.2-alpine
    container_name: aiops-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass aiops123
    volumes:
      - redis_data:/data
    networks:
      - aiops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # vLLM服务 - LLM推理服务 (CPU模式)
  vllm:
    image: vllm/vllm-openai:v0.4.2
    container_name: aiops-vllm
    ports:
      - "8000:8000"
    environment:
      CUDA_VISIBLE_DEVICES: ""
      VLLM_WORKER_USE_RAY: "false"
    command: 
      - --model
      - Qwen/Qwen2.5-1.5B-Instruct
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --max-model-len
      - "409      - --device
      - cpu
      - --enforce-eager
      - --tensor-parallel-size
      - "1"
      - --trust-remote-code
    volumes:
      - huggingface_cache:/root/.cache/huggingface
    networks:
      - aiops-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 120s
      timeout: 60s
      retries: 3
      start_period: 300s
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # API服务 - FastAPI应用
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: aiops-api
    ports:
      - "8888:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://aiops_user:aiops_pass@mysql:3306/aiops
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=aiops123
      - WEAVIATE_URL=http://weaviate:8080
      - REDIS_URL=redis://:aiops123@redis:6379/0
      - VLLM_API_BASE=http://vllm:8000/v1
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./config:/app/config
    networks:
      - aiops-network
    depends_on:
      mysql:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      weaviate:
        condition: service_healthy
      redis:
        condition: service_healthy
      # vllm:
      #   condition: service_healthy  # 暂时禁用vLLM依赖
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # Prometheus监控
  prometheus:
    image: prom/prometheus:latest
    container_name: aiops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - aiops-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # cAdvisor - Docker容器监控
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: aiops-cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - aiops-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # Grafana仪表盘
  grafana:
    image: grafana/grafana:latest
    container_name: aiops-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=aiops123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
    networks:
      - aiops-network
    depends_on:
      - prometheus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: aiops-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - aiops-network
    depends_on:
      - api
      - grafana
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'

volumes:
  mysql_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  weaviate_data:
  redis_data:
  prometheus_data:
  grafana_data:
  huggingface_cache:

networks:
  aiops-network:
    driver: bridge