global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API服务监控
  - job_name: 'aiops-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Neo4j监控 (需要启用metrics插件)
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: '/metrics'
    scrape_interval: 30s
    basic_auth:
      username: 'neo4j'
      password: 'aiops123'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093