global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'aiops-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # API服务监控
  - job_name: 'aiops-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'aiops-api'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'fastapi-backend'

  # Docker容器监控 (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'cadvisor'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'container-monitor'

  # Grafana监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_name
        replacement: 'aiops-grafana'
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'visualization'

  # 注意: Redis、MySQL、Weaviate、Neo4j 没有原生/metrics端点
  # 这些服务通过cAdvisor在容器级别进行监控，提供CPU、内存、网络、磁盘I/O指标

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093